---
- name: Ensure installation scenario is selected
  fail:
    msg: "Please choose either the stable or git scenario."
  when:
    - not netbox_stable
    - not netbox_git

- name: Ensure only one scenario is enabled
  fail:
    msg: "Please select only one scenario."
  when:
    - netbox_stable and netbox_git

- name: Ensure a DB connection method is defined
  fail:
    msg: "Please define either database_socket (local) or database_host/database_password (TCP)."
  when:
    - netbox_database_socket is not defined
    - netbox_database_host is not defined or (netbox_database_host is defined and netbox_database_password is not defined)

- name: Ensure only one DB connection method is defined
  fail:
    msg: "Please define only one database connection method."
  when:
    - netbox_database_socket is defined and netbox_database_host is defined

- name: Ensure Python version is valid
  fail:
    msg: "Please set netbox_python to either 2 or 3."
  when:
    - netbox_python not in [2, 3]
