---
- name: Install pyparsing and appdirs modules via pip
  pip:
    virtualenv: "{{ netbox_current_path }}/venv-py{{ netbox_python }}"
    virtualenv_python: "/usr/bin/python{{ netbox_python }}"
    name: "{{ item }}"
    state: present
  with_items:
    - pyparsing
    - appdirs

