---
- name: Install pyparsing and appdirs modules via pip
  pip:
    virtualenv: "{{ netbox_current_path }}/venv-py{{ netbox_python }}"
    virtualenv_python: "{{ netbox_python3_binary if (netbox_python == 3) else netbox_python2_binary }}"
    name: "{{ item }}"
    state: present
  with_items:
    - pyparsing
    - appdirs
