---
- name: Clone Netbox from Github
  git:
    repo: https://github.com/digitalocean/netbox.git
    dest: "{{ netbox_git_path }}"
    update: no

- name: Change owner to netbox
  file: 
    dest: "{{ netbox_git_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"

- name: Create a link to active release
  file:
    src: "{{ netbox_git_path }}"
    dest: "{{ netbox_current_path }}"
    state: link
