---
- name: Clone Netbox from Github
  git:
    repo: https://github.com/digitalocean/netbox.git
    dest: "{{ netbox_git_path }}"
    update: no

- name: Create a link to active release
  file:
    src: "{{ netbox_git_path }}"
    dest: "{{ netbox_current_path }}"
    state: link

