---
- name: Install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ netbox_current_path }}/venv-py{{ netbox_python }}"

- name: Write gunicorn config
  template:
    src: templates/gunicorn_config.py.j2
    dest: "{{ netbox_current_path }}/netbox/gunicorn_config.py"

- name: Write supervisord config
  template:
    src: templates/supervisor.conf.j2
    dest: /etc/supervisor/conf.d/netbox.conf

- name: Restart and Enable supervisord
  service:
    name: supervisor
    state: restarted
    enabled: yes
