---
# handlers file for lae.netbox
- name: restart netbox.socket
  systemd:
    name: netbox.socket
    state: restarted
    daemon_reload: true

- name: restart netbox.service
  systemd:
    name: netbox.service
    state: restarted
    daemon_reload: true

- name: reload netbox.service
  systemd:
    name: netbox.service
    state: reloaded

- name: restart netbox-rqworker.service
  systemd:
    name: "netbox-rqworker@{{ item }}.service"
    state: restarted
    daemon_reload: true
  with_sequence: count="{{ netbox_rqworker_processes }}"
