---
- name: Converge
  hosts: all
  become: true
  vars:
    redis_version: 6.2.1
    netbox_stable_version: 2.10.8
    netbox_stable: true
    netbox_socket: "0.0.0.0:80"
    netbox_superuser_password: netbox
    netbox_superuser_create_token: true
    netbox_config:
      ALLOWED_HOSTS:
        - "{{ inventory_hostname }}"
        # The following should not be used in production, probably.
        # This playbook gets used by Vagrant where we don't know the actual hostname.
        - "*"
      MEDIA_ROOT: "{{ netbox_shared_path }}/media"
      REPORTS_ROOT: "{{ netbox_shared_path }}/reports"
      SCRIPTS_ROOT: "{{ netbox_shared_path }}/scripts"
    netbox_database_socket: "{{ postgresql_unix_socket_directories[0] }}"
    # webhooks
    netbox_webhooks_enabled: true
    # db
    postgresql_users:
      - name: "{{ netbox_database_user }}"
        role_attr_flags: CREATEDB,NOSUPERUSER
    ## REDIS server install
    redis_bind: 127.0.0.1
    netbox_rqworker_processes: 2
  roles:
    - geerlingguy.postgresql
    - davidwittman.redis
    - ansible-role-netbox
