---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian-9
    box: generic/debian9
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: default
verifier:
  name: testinfra
  lint: |
    set -e
    flake8
