---
dependency:
  name: galaxy
driver:
  name: docker
  provider:
    name: centos8
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos8
    image: geerlingguy/docker-centos8-ansible:latest
    command: /sbin/init
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: default
verifier:
  name: testinfra
  lint: |
    set -e
    flake8
