---
- hosts: netbox
  become: yes
  vars:
    netbox_stable: true
    netbox_database_socket: "{{ postgresql_unix_socket_directories[0] }}"
    netbox_superuser_password: netbox
    netbox_socket: "0.0.0.0:80"
    netbox_config:
      ALLOWED_HOSTS:
        - localhost
        - 127.0.0.1
        - "{{ inventory_hostname }}"
      MEDIA_ROOT: "{{ netbox_shared_path }}/media"
      REPORTS_ROOT: "{{ netbox_shared_path }}/reports"
    netbox_keep_uwsgi_updated: true
    postgresql_version: "10"
    postgresql_packages:
      - postgresql10
      - postgresql10-server
      - postgresql10-contrib
      - postgresql10-libs
    postgresql_users:
      - name: netbox
        role_attr_flags: CREATEDB,NOSUPERUSER
  pre_tasks:
    - name: Enable Subscription Manager Repos
      rhsm_repository:
        name: "{{ item }}"
      loop:
        - rhel-*-optional-rpms
        - rhel-*-extras-rpms
    - name: Enable/Install EPEL Repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - name: Enable/Install PostgreSQL Repo
      yum:
        name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-2.noarch.rpm

  roles:
    - geerlingguy.postgresql
    - lae.netbox
# Using this playbook installs the EPEL and PostgreSQL repos on the host.
# Use at your own risk.
